In [1]:
from pathlib import Path
from lexos.dtm import DTM
from lexos.cluster.kmeans import KMeansCluster

In [3]:
pirate_path = Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/HenryWP_ThePirate.txt")
rip_path = Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/Irving_RipVanWInkle.txt")

with open(pirate_path, "r", encoding="utf-8") as f:
    pirate_text = f.read()

with open(rip_path, "r", encoding="utf-8") as f:
    rip_text = f.read()

docs = [pirate_text.split(), rip_text.split()]  # Tokenize simply by splitting on space
labels = ["The Pirate", "Rip Van Winkle"]

In [4]:
dtm = DTM()
dtm(docs, labels)

In [5]:
kmeans = KMeansCluster(k=2)
assignments = kmeans(dtm)

print(f"Cluster assignments: {dict(zip(labels, assignments))}")

Cluster assignments: {'The Pirate': 0, 'Rip Van Winkle': 1}


In [6]:
kmeans.plot_2d(show=True)

In [15]:

from pathlib import Path
from lexos.dtm import DTM
from lexos.cluster.kmeans import KMeansCluster


pirate_path = Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/HenryWP_ThePirate.txt")
rip_path    = Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/Irving_RipVanWInkle.txt")
third_path  = Path("//Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/Lippard_BelOfPrairieEden.txt")  # ← your 3rd file

# 2) read in the raw text
texts = []
for p in (pirate_path, rip_path, third_path):
    texts.append(p.read_text(encoding="utf-8"))

# 3) super-simple tokenization + labels
docs   = [t.split() for t in texts]
labels = ["The Pirate", "Rip Van Winkle", "My Third Doc"]  # tweak as you like



In [16]:
# 4) build DTM and run KMeans
dtm = DTM()
dtm(docs, labels)

kmeans = KMeansCluster(k=3)      # now k=3
assignments = kmeans(dtm)

In [17]:
# 5) show which doc landed in which cluster
print("Cluster assignments:", dict(zip(labels, assignments)))


Cluster assignments: {'The Pirate': 2, 'Rip Van Winkle': 0, 'My Third Doc': 1}


In [18]:
# 6) and finally, the 3D plot!
kmeans.plot_3d(show=True)


In [22]:
from sklearn.decomposition import PCA
import numpy as np
import pandas as pd

matrix = kmeans._get_valid_matrix()
labels = kmeans.labels
assigns = kmeans.cluster_assignments

pca = PCA(n_components=3)
coords = pca.fit_transform(matrix)

print("Matrix shape:", matrix.shape)
print("Any NaNs?:", np.isnan(matrix).any())
print("Explained variance ratio:", pca.explained_variance_ratio_)
print("Coords (first 5 rows):\n", coords[:5])
print("Cluster assignments:", assigns)

df = pd.DataFrame(coords, columns=["PC1", "PC2", "PC3"])
df["cluster"] = assigns
df["document"] = labels
print("Combined DataFrame:\n", df)


Matrix shape: (3, 6874)
Any NaNs?: False
Explained variance ratio: [9.97211938e-01 2.78806227e-03 1.44669592e-32]
Coords (first 5 rows):
 [[-1.69921688e+03  1.25045285e+02  2.48015129e-13]
 [-1.19844107e+03 -1.40332917e+02  2.48015129e-13]
 [ 2.89765795e+03  1.52876318e+01  2.48015129e-13]]
Cluster assignments: [2 0 1]
Combined DataFrame:
            PC1         PC2           PC3  cluster        document
0 -1699.216881  125.045285  2.480151e-13        2      The Pirate
1 -1198.441073 -140.332917  2.480151e-13        0  Rip Van Winkle
2  2897.657955   15.287632  2.480151e-13        1    My Third Doc


In [23]:

paths = [
    Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/HenryWP_ThePirate.txt"),
    Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/Irving_RipVanWInkle.txt"),
    Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/Lippard_BelOfPrairieEden.txt"),
    Path("/Users/tusharkoushik/Documents/GitHub/uv_lexos/src/lexos/cluster/FilesToUse/Melville_MobyDick.txt"),  # ← add your 4th file here
]

texts = [p.read_text(encoding="utf-8") for p in paths]
docs   = [t.split() for t in texts]
labels = ["The Pirate", "Rip Van Winkle", "Bel of Prairie Eden", "Moby DIct"]

# Cell 3 (re-run clustering with k=4):
dtm = DTM()
dtm(docs, labels)

kmeans = KMeansCluster(k=4)
assignments = kmeans(dtm)

print("Cluster assignments:", dict(zip(labels, assignments)))

# Cell 4 (plot in 3D):
kmeans.plot_3d(show=True)


Cluster assignments: {'The Pirate': 3, 'Rip Van Winkle': 0, 'My Third Doc': 2, 'My Fourth Doc': 1}
